// <auto-generated />
namespace LibraryManagment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class initials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initials));
        
        string IMigrationMetadata.Id
        {
            get { return "202002111702433_initials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
